In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('/content/drive/My Drive/Credit Card/creditcard.csv')
df.head()

   Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

In [3]:
df.dtypes

Time      float64
V1        float64
V2        float64
V3        float64
V4        float64
V5        float64
V6        float64
V7        float64
V8        float64
V9        float64
V10       float64
V11       float64
V12       float64
V13       float64
V14       float64
V15       float64
V16       float64
V17       float64
V18       float64
V19       float64
V20       float64
V21       float64
V22       float64
V23       float64
V24       float64
V25       float64
V26       float64
V27       float64
V28       float64
Amount    float64
Class       int64
dtype: object

In [4]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [0]:
from sklearn.ensemble import IsolationForest
from sklearn.model_selection import train_test_split

In [0]:
inliers = df[df.Class==0]
inliers = inliers.drop(['Class'], axis=1)
outliers = df[df.Class==1]
outliers = outliers.drop(['Class'], axis=1)
inliers_train, inliers_test = train_test_split(inliers, test_size=0.30, random_state=42)

In [7]:
inliers_train.head()

            Time        V1        V2  ...       V27       V28  Amount
182516  125434.0 -1.375072  0.789565  ... -0.060415 -0.114552    25.0
182203  125303.0 -0.364812 -0.227765  ...  0.019981  0.038710    15.0
90215    62923.0  0.287335 -1.520930  ... -0.026654  0.097686   450.0
189554  128452.0 -0.427464  0.513051  ...  0.027876  0.133560     2.0
105175   69394.0  1.064630 -0.272178  ...  0.086035  0.013312    39.0

[5 rows x 30 columns]

In [8]:
inliers_test.head()

            Time        V1        V2  ...       V27       V28  Amount
138028   82450.0  1.314539  0.590643  ... -0.034321  0.031692    0.76
63099    50554.0 -0.798672  1.185093  ... -0.396030 -0.112901    4.18
73411    55125.0 -0.391128 -0.245540  ...  0.163716  0.239582   15.00
164247  116572.0 -0.060302  1.065093  ... -0.023634  0.042330   57.00
148999   90434.0  1.848433  0.373364  ... -0.019823 -0.042682    0.00

[5 rows x 30 columns]

In [0]:
model = IsolationForest()
model.fit(inliers_train)
inlier_pred_test = model.predict(inliers_test)
outlier_pred = model.predict(outliers)

In [10]:
print("Accuracy in Detecting Legit Cases:", list(inlier_pred_test).count(1)/inlier_pred_test.shape[0])
print("Accuracy in Detecting Fraud Cases:", list(outlier_pred).count(-1)/outlier_pred.shape[0])

Accuracy in Detecting Legit Cases: 0.9652148426050765
Accuracy in Detecting Fraud Cases: 0.8109756097560976